const express = require('express');
const router  = express.Router();
const User    = require('../models/User');
const { protect } = require('../middleware/auth.middleware');
const { sendSMS, sendWhatsApp } = require('../config/twilio');
const sendToken = (user, code, res) => { const token = user.generateToken(); user.password=undefined; res.status(code).json({ success:true, token, user:{ _id:user._id, name:user.name, mobile:user.mobile, email:user.email, village:user.village, role:user.role } }); };

router.post('/register', async (req,res) => { try { const { name,mobile,password,village } = req.body; if(!name||!mobile||!password) return res.status(400).json({success:false,message:'Naam, mobile aur password zaroori hai'}); if(await User.findOne({mobile})) return res.status(400).json({success:false,message:'Mobile already registered'}); const user = await User.create({name,mobile,password,village}); sendWhatsApp(`+91${mobile}`,`🎉 Namaste ${name} ji!\nUG Bazaar mein swagat!\n📞 8390901925`).catch(()=>{}); sendToken(user,201,res); } catch(e){ res.status(500).json({success:false,message:e.message}); }});
router.post('/login', async (req,res) => { try { const {mobile,password} = req.body; if(!password) return res.status(400).json({success:false,message:'Password daalo'}); const user = await User.findOne({mobile}).select('+password'); if(!user||!await user.comparePassword(password)) return res.status(401).json({success:false,message:'Galat mobile ya password'}); sendToken(user,200,res); } catch(e){ res.status(500).json({success:false,message:e.message}); }});
router.post('/send-otp', async (req,res) => { try { const {mobile}=req.body; const user=await User.findOne({mobile}); if(!user) return res.status(404).json({success:false,message:'Mobile registered nahi hai'}); const otp=user.generateOTP(); await user.save({validateBeforeSave:false}); await sendSMS(`+91${mobile}`,`🔐 UG Bazaar OTP: ${otp}\nValid 10 min.`); res.json({success:true,message:'OTP bheja gaya'}); } catch(e){ res.status(500).json({success:false,message:e.message}); }});
router.post('/verify-otp', async (req,res) => { try { const {mobile,otp}=req.body; const user=await User.findOne({mobile}); if(!user||!user.verifyOTP(otp)) return res.status(400).json({success:false,message:'Galat ya expired OTP'}); user.otp=undefined; user.isVerified=true; await user.save({validateBeforeSave:false}); sendToken(user,200,res); } catch(e){ res.status(500).json({success:false,message:e.message}); }});
router.post('/forgot-password', async (req,res) => { try { const {mobile}=req.body; const user=await User.findOne({mobile}); if(!user) return res.status(404).json({success:false,message:'Mobile registered nahi'}); const otp=user.generateOTP(); await user.save({validateBeforeSave:false}); await sendSMS(`+91${mobile}`,`🔐 Reset OTP: ${otp}\nValid 10 min.`); res.json({success:true}); } catch(e){ res.status(500).json({success:false,message:e.message}); }});
router.post('/reset-password', async (req,res) => { try { const {mobile,otp,newPassword}=req.body; const user=await User.findOne({mobile}).select('+password'); if(!user||!user.verifyOTP(otp)) return res.status(400).json({success:false,message:'Galat OTP'}); user.password=newPassword; user.otp=undefined; await user.save(); res.json({success:true,message:'Password reset hua!'}); } catch(e){ res.status(500).json({success:false,message:e.message}); }});
router.get('/me', protect, async (req,res) => { try { res.json({success:true,user:req.user}); } catch(e){ res.status(500).json({success:false,message:e.message}); }});
router.put('/update-profile', protect, async (req,res) => { try { const user=await User.findByIdAndUpdate(req.user._id,req.body,{new:true}); res.json({success:true,user}); } catch(e){ res.status(500).json({success:false,message:e.message}); }});
module.exports = router;
